In [1]:
import numpy as np

## Arrays

In [2]:
#initialize an array
arr = np.array([-1,2,5], dtype=np.float32)

In [3]:
#print the representation of the array
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


In [4]:
arr1 = np.array([[0,1,2],[3,4,5]], dtype=np.float32)

In [5]:
print(repr(arr1))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


### array type 'upcasts' to the highest level type

In [6]:
#double>float>int
arr2 = np.array([0, 0.2 ,2])
print(repr(arr2))

array([0. , 0.2, 2. ])


## Copying


In [7]:
a = np.array([0,1])
b = np.array([9,8])
c = a
d = b.copy()
# c is a reference to a
# d is a copy of a
print('Array a: {}'.format(repr(a)))
c[0] = 5 # first element of a is changed to 5
print('Array a: {}'.format(repr(a)))

d[0] = 6
print('Array b: {}'.format(repr(b)))
print('Array d: {}'.format(repr(d)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])
Array d: array([6, 8])


## Casting

### use astype to typecast
#### (the default type is 'int64')

In [8]:
 
arr = np.array([0,1,2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


## NaN

### use np.nan to act as a placeholder

In [9]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


#### np.nan cannot be an 'int' type

In [10]:
#the following will throw an exception
np.array([np.nan, 1, 2], dtype = np.int32)

ValueError: cannot convert float NaN to integer

## Infinity

### use 'np.inf' to represent +ve infinity and '-np.inf' to represent -ve infinity

In [ ]:
print(np.inf > 100000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 5])
print(repr(arr))

#### np.inf cannot take 'int' data type

In [ ]:
#the following will throw an exception
np.array([np.inf, 1, 2], dtype = np.int32)

# Excercise 1
###### The first array we'll create comes straight from a list of integers and np.nan. The list contains np.nan as the first element, and the integers from 2 to 5, inclusive, as the next four elements.

In [ ]:
#solution
arr = np.array([np.nan, 1, 3, 4, 5])
print(arr)

###### We now want to copy the array so we can change the first element to 10. This way we don't modify the original array.

In [ ]:
#solution
arr2 = arr.copy()
arr2[0] = 10
print(arr)
print(arr2)

###### The next two arrays will use floating point numbers. The first array will be upcast to floating point numbers, while we manually cast the second array using np.float32.

In [ ]:
float_arr = np.array([1, 5.4, 3])
print(float_arr.dtype)
float_arr2 = arr2.astype(np.float32)
print(float_arr2.dtype)

###### The final array will be a multi-dimensional array, specifically a 2-D matrix. The 2-D matrix will have the integers 1, 2, 3 in its first row, and the integers 4, 5, 6 in its second row. We'll also manually set its type to np.float32.

In [ ]:
#solution
matrix = np.array([[1, 2 ,3],[4, 5, 6]], dtype = np.float32)
print(repr(matrix))

## Ranged Data

### use 'np.arange' to create ranged data arrays

#### Note: The Lower end is inclusive and the upper end is exclusive


In [17]:
arr = np.arange(5)
#from 0 to 4 
print(repr(arr))

arr = np.arange(5.1)
#float point, note that 5.0 also gets printed as the max here is '5.1'
print(repr(arr))

arr = np.arange(-1,4)
#if two arguments, then start and max
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
#if three arguments, then start, max and increment
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


### To specify a predefined number of elements in the range, use 'np.linspace'. Takes a 'num' argument

In [22]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))
#default type is float and default value for num is '50'

arr = np.linspace(5, 11)
print(repr(arr))
#also, the endpoint is inclusive unless is set to false

arr = np.linspace(5,11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([ 5.        ,  5.12244898,  5.24489796,  5.36734694,  5.48979592,
        5.6122449 ,  5.73469388,  5.85714286,  5.97959184,  6.10204082,
        6.2244898 ,  6.34693878,  6.46938776,  6.59183673,  6.71428571,
        6.83673469,  6.95918367,  7.08163265,  7.20408163,  7.32653061,
        7.44897959,  7.57142857,  7.69387755,  7.81632653,  7.93877551,
        8.06122449,  8.18367347,  8.30612245,  8.42857143,  8.55102041,
        8.67346939,  8.79591837,  8.91836735,  9.04081633,  9.16326531,
        9.28571429,  9.40816327,  9.53061224,  9.65306122,  9.7755102 ,
        9.89795918, 10.02040816, 10.14285714, 10.26530612, 10.3877551 ,
       10.51020408, 10.63265306, 10.75510204, 10.87755102, 11.        ])
array([ 5,  7,  9, 11], dtype=int32)


## Reshaping Data 

In [27]:
arr = np.arange(8)
print(repr(arr))

reshaped_arr = np.reshape(arr, (2,4)) #2nd argument: [rowsxcolumn]
print(repr(reshaped_arr))

reshaped_arr = np.reshape(arr, (-1,2,2)) #'-1' to contain the shape
#gives two 2x2 arrays
print(repr(reshaped_arr))

array([0, 1, 2, 3, 4, 5, 6, 7])
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])


### use 'flatten()' funtion to convert reshaped arrays into an one-dimentional array.

In [28]:
reshaped_arr = reshaped_arr.flatten()
print(repr(reshaped_arr))

array([0, 1, 2, 3, 4, 5, 6, 7])


## Transposing

### Use 'np.transpose' function to transpose the array

In [33]:
arr = np.reshape(arr, (4,2))
print(repr(arr))

transposed_arr = np.transpose(arr)
#(4,2) becomes (2,4)
print(repr(transposed_arr))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])


### use 'axes' to define new permutation of the dimensions (i.e the order of transpose). The dafault value for a 3-d arrays is [2,1,0]

In [44]:
arr = np.arange(24)
arr = np.reshape(arr, (3,4,2))
print(repr(arr))
transposed = np.transpose(arr, axes = (2,1,0))
print(repr(transposed))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])
array([[[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]],

       [[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]]])


## Zeroes and Ones

### Use 'np.zeros' to generate '0s' and 'np.ones' to generate '1s' 

In [48]:
arr = np.zeros(4)
#create an one dimentional array 
print(repr(arr)) 

arr = np.ones((3,2), dtype = np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)


### use 'np.zeros_like' to create an array of the same shape as any other array

In [54]:
arr = np.arange(20)
arr = np.reshape(arr, (5,4))
print(repr(arr))

arr1 = np.ones_like(arr)
print(repr(arr1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])


# Excercise 2

##### Our initial array will just be all the integers from 0 to 11, inclusive. We'll also reshape it so it has three dimensions.

In [58]:
#solution
arr = np.arange(12)
reshaped = np.reshape(arr, (2,3,2))
print(repr(reshaped))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])


##### Next we want to get a flattened version of the reshaped array (the flattened version is equivalent to arr), as well as a transposed version. For the transposed version of reshaped, we use a permutation of (1, 2, 0).

In [59]:
#solution
flattened = reshaped.flatten()
print(repr(flattened))
transposed = np.transpose(reshaped, axes = (1,2,0))
print(repr(transposed))


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])


##### We'll create an array of 5 elements, all of which are 0. We'll also create an array with the same shape as transposed, but containing only 1 as the elements.

In [60]:
#solution 
zeros_arr = np.zeros(5)
print(repr(zeros_arr))
ones_arr = np.ones_like(transposed)
print(repr(ones_arr))

array([0., 0., 0., 0., 0.])
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])


##### The final array will contain 101 evenly spaced numbers between -3.5 and 1.5, inclusive. Since they are evenly spaced, the difference between adjacent numbers is 0.05.

In [62]:
#solution
points = np.linspace(-3.5, 1.5, num=101)
print(repr(points))

array([-3.5 , -3.45, -3.4 , -3.35, -3.3 , -3.25, -3.2 , -3.15, -3.1 ,
       -3.05, -3.  , -2.95, -2.9 , -2.85, -2.8 , -2.75, -2.7 , -2.65,
       -2.6 , -2.55, -2.5 , -2.45, -2.4 , -2.35, -2.3 , -2.25, -2.2 ,
       -2.15, -2.1 , -2.05, -2.  , -1.95, -1.9 , -1.85, -1.8 , -1.75,
       -1.7 , -1.65, -1.6 , -1.55, -1.5 , -1.45, -1.4 , -1.35, -1.3 ,
       -1.25, -1.2 , -1.15, -1.1 , -1.05, -1.  , -0.95, -0.9 , -0.85,
       -0.8 , -0.75, -0.7 , -0.65, -0.6 , -0.55, -0.5 , -0.45, -0.4 ,
       -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 , -0.05,  0.  ,  0.05,
        0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,  0.5 ,
        0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,
        1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,  1.4 ,
        1.45,  1.5 ])


# Math

## Arithmetic

In [71]:
arr = np.array([[1,2],[3,4]])
print(repr(arr + 1))
print(repr(arr - 1.2))
print(repr(arr / 2))
print(repr(arr ** 2)) #power '2' to the values
print(repr(arr ** 0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [74]:
#The code below converts Fahrenheit to Celsius in NumPy
def f2c(temps):
    return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


#### Note: Performing arithmetic on NumPy arrays 'does not change the original array'

## Non-linear Functions

### np.exp - perform a base e exponential
### np.exp2 - perform a base 2 exponential
### np.log - perform logarithmic functions
### np.power - normal power operation

In [82]:
arr = np.array([[1,2], [3,4]])
print(repr(np.exp(arr)))
print(repr(np.exp2(arr)))
print(repr(np.log(arr)))
print(repr(np.log2(arr)))

print(np.pi) #value of pi
print(np.e) #value of e

print(repr(np.power(arr, 2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])
array([[0.       , 1.       ],
       [1.5849625, 2.       ]])
3.141592653589793
2.718281828459045
array([[ 1,  4],
       [ 9, 16]])


NumPy is not limited to the above mentioned mathematical funtions:
https://docs.scipy.org/doc/numpy/reference/routines.math.html  

## Matrix Multiplication

### use 'np.matmul' for multiplying 2 vector/matrix arrays
### Note: 
the dimensions of the two input matrices must be valid for a matrix multiplication. Specifically, the second dimension of the first matrix must equal the first dimension of the second matrix, otherwise 'np.matmul' will result in a 'ValueError'

In [91]:
arr1 = np.arange(4)
print(arr1)
arr2 = np.arange(5,9)
print(arr2)

print(np.matmul(arr2, arr1))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

#this will throw an error
print(repr(np.matmul(arr3, arr3)))

[0 1 2 3]
[5 6 7 8]
44
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)